language: python
python:
  - "3.5"
install:
  - "pip install pylint"
  - "pip install nose"
before_script:
  - "pylint -E simplegallery.py"
script:
  - nosetests --with-coverage
after_success:
  - coveralls
